kmerfinder/urls.py
from django.conf.urls import url

from . import views

app_name = 'kmerfinder'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^kmerfinder/$', views.DetailView, name='detail'),
]

kmerfindercloud/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^', include('kmerfinder.urls')),
    url(r'^admin/', admin.site.urls),
]

lib/django/conf/project_template/project_name/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

kmerfinder/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
# Create your models here.
def handle_uploaded_file(f):
    with open('kmerfinder/name.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

kmerfinder/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)
	
class UploadFileForm(forms.Form):
    enctype="multipart/form-data"
    file = forms.FileField(label="FILE")

kmerfinder/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from kmerfinder.forms import UploadFileForm
from .models import handle_uploaded_file

# Create your views here.
def index(request):
    return render(request, 'kmerfinder/index.html')
	
def DetailView(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = UploadFileForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
    else:
        form = UploadFileForm()
    return render(request, 'kmerfinder/detail.html', {'form': form})
	

kmerfinder/templates/kmerfinder/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Fushamalaik</title>
<meta charset="utf-8">
<!-- Google web fonts -->
<!-- JavaScript Includes -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>



<link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700" rel='stylesheet'/>
<link href="/static/kmerfinder/css/upload.css" rel="stylesheet"/>
<link rel="icon" href="/static/kmerfinder/images/favicon.ico">
<link rel="stylesheet" href="/static/kmerfinder/css/style.css">
<link rel="stylesheet" href="/static/kmerfinder/css/slider.css">
<script src="/static/kmerfinder/js/jquery.js"></script>
<script src="/static/kmerfinder/js/jquery-migrate-1.1.1.js"></script>
<script src="/static/kmerfinder/js/superfish.js"></script>
<script src="/static/kmerfinder/js/jquery.equalheights.js"></script>
<script src="/static/kmerfinder/js/jquery.easing.1.3.js"></script>
<script src="/static/kmerfinder/js/tms-0.4.1.js"></script>



<script>
$(window).load(function () {
    $('.slider')._TMS({
        show: 0,
        pauseOnHover: false,
        prevBu: '.prev',
        nextBu: '.next',
        playBu: false,
        duration: 800,
        preset: 'fade',
        pagination: true, //'.pagination',true,'<ul></ul>'
        pagNums: false,
        slideshow: 8000,
        numStatus: false,
        banners: true,
        waitBannerAnimation: false,
        progressBar: false
    })
});
</script>
</head>
<body>
<header>
  <div class="container_12">
    <div class="grid_12">
      <div class="clear"></div>
      <div class="menu_block">
        <nav>
          <ul class="sf-menu">
            <li class="current"><a href="{% url 'kmerfinder:index'%}">HOME</a></li>
            <li class="with_ul"><a href="about.html">SERVICES</a>
              <ul>
                <li><a href="{% url 'kmerfinder:detail'%}">KmerFinder</a></li>
                <li><a href="#">ResFinder</a></li>
                <li><a href="#">MLST</a></li>
				<li><a href="#">NDtree</a></li>
			  </ul>
            </li>
            <li><a href="practice.html">RESEARCH</a></li>
            <li><a href="clients.html">TUTORIAL</a></li>
            <li><a href="contacts.html">CONTACTS</a></li>
          </ul>
        </nav>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</header>

<form id="upload" method="post" action="/static/kmerfinder/php/upload.php" enctype="multipart/form-data">
	<div id="drop">
		Drop Here
		<a>Browse</a>
		<input type="file" name="upl" multiple />
	</div>
	<ul>
	<!-- The file uploads will be shown here -->
	</ul>

</form>
<script src="/static/kmerfinder/js/jquery.knob.js"></script>
<!-- Our main JS file -->
<script src="/static/kmerfinder/js/uploadscript.js"></script>
<!-- jQuery File Upload Dependencies -->
<script src="/static/kmerfinder/js/jquery.ui.widget.js"></script>
<script src="/static/kmerfinder/js/jquery.iframe-transport.js"></script>
<script src="/static/kmerfinder/js/jquery.fileupload.js"></script>
</body>
</html>

kmerfinder/templates/kmerfinder/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Fushamalaik</title>
<meta charset="utf-8">
<link rel="icon" href="images/favicon.ico">
<link rel="shortcut icon" href="images/favicon.ico">
<link rel="stylesheet" href="/static/kmerfinder/css/style.css">
<link rel="stylesheet" href="/static/kmerfinder/css/slider.css">
<script src="/static/kmerfinder/js/jquery.js"></script>
<script src="/static/kmerfinder/js/jquery-migrate-1.1.1.js"></script>
<script src="/static/kmerfinder/js/superfish.js"></script>
<script src="/static/kmerfinder/js/jquery.equalheights.js"></script>
<script src="/static/kmerfinder/js/jquery.easing.1.3.js"></script>
<script src="/static/kmerfinder/js/tms-0.4.1.js"></script>
<script>
$(window).load(function () {
    $('.slider')._TMS({
        show: 0,
        pauseOnHover: false,
        prevBu: '.prev',
        nextBu: '.next',
        playBu: false,
        duration: 800,
        preset: 'fade',
        pagination: true, //'.pagination',true,'<ul></ul>'
        pagNums: false,
        slideshow: 8000,
        numStatus: false,
        banners: true,
        waitBannerAnimation: false,
        progressBar: false
    })
});
</script>
</head>
<body>
<header>
  <div class="container_12">
    <div class="grid_12">
      <div class="clear"></div>
      <div class="menu_block">
        <nav>
          <ul class="sf-menu">
            <li class="current"><a href="index.html">HOME</a></li>
            <li class="with_ul"><a href="about.html">SERVICES</a>
              <ul>
                <li><a href="{% url 'kmerfinder:detail'%}">KmerFinder</a></li>
                <li><a href="#">ResFinder</a></li>
                <li><a href="#">MLST</a></li>
				<li><a href="#">NDtree</a></li>
			  </ul>
            </li>
            <li><a href="practice.html">RESEARCH</a></li>
            <li><a href="clients.html">TUTORIAL</a></li>
            <li><a href="contacts.html">CONTACTS</a></li>
          </ul>
        </nav>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</header>
<div class="top_block">
  <div class="slider-relative">
    <div class="slider-block">
      <div class="slider">
        <ul class="items">
          <li><img src="/static/kmerfinder/images/slide_human-chromosomes.jpg" alt="">
            <div class="banner">User-friendly<br>
              experience</div>
          </li>
          <li><img src="/static/kmerfinder/images/slide_dna-human-genome.jpg" alt="">
            <div class="banner">Instant<br>
              results</div>
          </li>
          <li><img src="/static/kmerfinder/images/slide2.jpg" alt="">
            <div class="banner">Based on<br>
              science</div>
          </li>
          <li><img src="/static/kmerfinder/images/slide_DNAhjul.jpg" alt="">
            <div class="banner">Reliable and<br>
              stable performance</div>
          </li>
        </ul>
      </div>
    </div>
  </div>

</body>
</html>